### ISSUE TITLE
Two-Step Verification

### ISSUE THREAD

**Issue by Kuroosh** [Auties00/Cobalt#265]
Hi, 

i'm pretty new here and i didn't found anything for Two-Step Verification.
Is it possible to Implement ( if it doesn't exists.. ) Two-Step Auth for the MobileBuild?
You can find this Option in the Whatsapp-Settings under Account => Verification by Two-Steps.
It will be important for us :)

Thx

**Comment by Auties00** [comment]
Added in latest commit, will be available in 3.4.10
