### ISSUE TITLE
When I tried to reconnect a registered phone number using the registered API, I found that the store displayed a status indicating that it was already connected, but in reality, it was not connected and could not send messages

### ISSUE THREAD

**Issue by topskymonk** [Auties00/Cobalt#320]

**Comment by Auties00** [comment]
can you show your code?

**Comment by topskymonk** [comment]
Whatsapp.mobileBuilder()
        .newConnection(UUID.fromString(myWhatsapp.getSessionId()))
        .registered()
        .get()
        .connectAndAwait()
        .join();
  }

**Comment by Auties00** [comment]
might want to try 3.4.5

**Comment by topskymonk** [comment]
OK

**Comment by topskymonk** [comment]
I tried reconnecting, but it still doesn't work. I'm constantly loading. v3.4.8

**Comment by friend-tom** [comment]
> Whatsapp.mobileBuilder() .newConnection(UUID.fromString(myWhatsapp.getSessionId())) .registered() .get() .connectAndAwait() .join(); }

@topskymonk Hello, may I know how the "myWhatsapp.getSessionId()" smile data is persisted in your local environment? Could you provide some complete examples of your use of mobileBuilder? I'm extremely grateful for your assistance, thank you!
