### ISSUE TITLE
"reason":"bad_token" （3.4.4）

### ISSUE THREAD

**Issue by LuckymanCN** [Auties00/Cobalt#325]
3.4.2-3.4.4
This is just an example for illustrative purposes. 

Long phone = 918641985364L;
for(int i=0;i<5;i++){
phone++;
  try {
        Whatsapp.mobileBuilder()
                    .newConnection()
                    .unregistered()
                    .register(phone, () -> {
                       System.out.println("Enter OTP: ");
                       return new Scanner(System.in).nextLine().trim();
                    })
                    .join();
         }(Exception e){
            System.out.println(e.getMessage());
         }
}

Only the first one works fine, start with the second
{"login":"918641985366","reason":"bad_token","status":"fail"}
it.auties.whatsapp.exception.RegistrationException: VerificationCodeResponse[number=918641985366, lid=0, status=ERROR, errorReason=UNKNOWN, method=null, codeLength=0, notifyAfter=0, retryAfter=0, voiceLength=0, voiceWait=0, smsWait=0, whatsappOtpWait=0, flashType=0, oldWait=0, securityCodeSet=false, whatsappOtpEligible=false]
{"login":"918641985367","reason":"bad_token","status":"fail"}
it.auties.whatsapp.exception.RegistrationException: VerificationCodeResponse[number=918641985367, lid=0, status=ERROR, errorReason=UNKNOWN, method=null, codeLength=0, notifyAfter=0, retryAfter=0, voiceLength=0, voiceWait=0, smsWait=0, whatsappOtpWait=0, flashType=0, oldWait=0, securityCodeSet=false, whatsappOtpEligible=false]
3.4.1 No problem。

**Comment by Auties00** [comment]
> 3.4.2-3.4.4 This is just an example for illustrative purposes.
> 
> Long phone = 918641985364L; for(int i=0;i<5;i++){ phone++; try { Whatsapp.mobileBuilder() .newConnection() .unregistered() .register(phone, () -> { System.out.println("Enter OTP: "); return new Scanner(System.in).nextLine().trim(); }) .join(); }(Exception e){ System.out.println(e.getMessage()); } }
> 
> Only the first one works fine, start with the second {"login":"918641985366","reason":"bad_token","status":"fail"} it.auties.whatsapp.exception.RegistrationException: VerificationCodeResponse[number=918641985366, lid=0, status=ERROR, errorReason=UNKNOWN, method=null, codeLength=0, notifyAfter=0, retryAfter=0, voiceLength=0, voiceWait=0, smsWait=0, whatsappOtpWait=0, flashType=0, oldWait=0, securityCodeSet=false, whatsappOtpEligible=false] {"login":"918641985367","reason":"bad_token","status":"fail"} it.auties.whatsapp.exception.RegistrationException: VerificationCodeResponse[number=918641985367, lid=0, status=ERROR, errorReason=UNKNOWN, method=null, codeLength=0, notifyAfter=0, retryAfter=0, voiceLength=0, voiceWait=0, smsWait=0, whatsappOtpWait=0, flashType=0, oldWait=0, securityCodeSet=false, whatsappOtpEligible=false] 3.4.1 No problem。

can you try 3.4.5?

**Comment by LuckymanCN** [comment]
The problem persists, should I do something after each loop?
Android and android business have the same problem.
Only the first one works fine, start with the second {"login":"918642034035","reason":"bad_token","status":"fail"}.

**Comment by LuckymanCN** [comment]
@Auties00 Thank you
