### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by LuckymanCN** [Auties00/Cobalt#326]
Sorry for disturbing you, but I have a question.Through reverse engineering, I know that when registering, the client will send an exist request before sending the code request. I am a novice here, and I don’t know why this part is ignored by the province. Can this function be added to Cobalt. Make the registration part of Cobalt perfect.

**Comment by Auties00** [comment]
> Sorry for disturbing you, but I have a question.Through reverse engineering, I know that when registering, the client will send an exist request before sending the code request. I am a novice here, and I don’t know why this part is ignored by the province. Can this function be added to Cobalt. Make the registration part of Cobalt perfect.
> 

i ignore it because if the number doesn't exist it will throw the same error as the exists method, so i saw no reason to add an additional request
