### ISSUE TITLE
mobileBuilder Cannot find signed pre key with id 5

### ISSUE THREAD

**Issue by hewrie** [Auties00/Cobalt#327]
<artifactId>whatsappweb4j</artifactId>
<version>3.4.8</version>

Connected
Jun 12, 2023 5:24:43 PM it.auties.whatsapp.socket.MessageHandler decodeMessage
WARNING: Cannot decode message(id: 3EB0E8F6ABFE947529BA32, from: 61xxxxxxxxx:17@s.whatsapp.net): Cannot find signed pre key with id 5

this.whatsapp = Whatsapp.mobileBuilder().lastConnection()
                    .registered().orElseThrow()
                    .addLoggedInListener(() -> System.out.println("Connected"))
                    .connect()
                    .join();
please help.. status whatsapp is online. but i can't send message.

**Comment by Auties00** [comment]
does this happen as soon as the session is started?

**Comment by hewrie** [comment]
Yes, after the session started and I tried to send a WhatsApp message to the API number, a warning appeared in the console, and the message was not sent.

**Comment by Auties00** [comment]
tracking in https://github.com/Auties00/Cobalt/issues/289
