### ISSUE TITLE
Error when trying to login to whatsapp mobile

### ISSUE THREAD

**Issue by GomesDev0001** [Auties00/Cobalt#329]
![image](https://github.com/Auties00/Cobalt/assets/113743540/43da7322-b5d4-4361-968e-aa4c7e7840b6)

**Comment by Auties00** [comment]
rate limited by WhatsApp, not a bug

**Comment by GomesDev0001** [comment]
como posso resolver?

**Comment by GomesDev0001** [comment]
Also, I noticed that the buttons on whatsapp web work, but when I entered my cell phone, the buttons do not appear, if I change the api to mobile, will it work?

**Comment by Auties00** [comment]
wait 3600 seconds / change number
