### ISSUE TITLE
Error with api sync.

### ISSUE THREAD

**Issue by GomesDev0001** [Auties00/Cobalt#330]
![image](https://github.com/Auties00/Cobalt/assets/113743540/6b9c0c17-e32b-4d32-93d0-a80ddac1cb36)
with the api in pom.xml

no api in pom.xml
![image](https://github.com/Auties00/Cobalt/assets/113743540/5dcc688b-e7d2-4e3b-b4f0-efda870244bd)

POM.XML:

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.bot.base</groupId>
    <artifactId>Bot-Name</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <java.version>17</java.version>
        <whatsapp4j.version>3.4.8</whatsapp4j.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <release>${java.version}</release>
                    <compilerArgument>--enable-preview</compilerArgument>
                    <compilerArgs>--enable-preview</compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <mainClass>me.bot.base.Main</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>jcenter</id>
            <name>jcenter-bintray</name>
            <url>https://jcenter.bintray.com</url>
        </repository>
    </repositories>

    <dependencies>
        
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>
        
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.20</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.github.auties00</groupId>
            <artifactId>whatsappweb4j</artifactId>
            <version>${whatsapp4j.version}</version>
        </dependency>

    </dependencies>
</project>

**Comment by GomesDev0001** [comment]
way I'm building the .jar

![image](https://github.com/Auties00/Cobalt/assets/113743540/57ab906b-a11d-49a6-83fc-2e1f13958de9)
![image](https://github.com/Auties00/Cobalt/assets/113743540/3398f40a-7808-417b-b044-7a33ed878f8f)
![image](https://github.com/Auties00/Cobalt/assets/113743540/8c73c337-96e7-4976-b295-b496f1c6a0ea)
![image](https://github.com/Auties00/Cobalt/assets/113743540/058d4ee0-bc60-4ff4-8343-90eb988e9490)
![image](https://github.com/Auties00/Cobalt/assets/113743540/925a8cb9-a025-4a8c-8125-01ca8aae0a18)

main empty
![image](https://github.com/Auties00/Cobalt/assets/113743540/576aab90-2d37-4686-b5c9-3a996ddf1fd2)

only with the presence of your api in the libraries does this happen, could you help solve it? I've tried everything

**Comment by Auties00** [comment]
> ![image](https://github.com/Auties00/Cobalt/assets/113743540/6b9c0c17-e32b-4d32-93d0-a80ddac1cb36)
> with the api in pom.xml
> 
> no api in pom.xml
> ![image](https://github.com/Auties00/Cobalt/assets/113743540/5dcc688b-e7d2-4e3b-b4f0-efda870244bd)
> 
> POM.XML:
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <project xmlns="http://maven.apache.org/POM/4.0.0"
>          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>          xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
>     <modelVersion>4.0.0</modelVersion>
> 
>     <groupId>com.bot.base</groupId>
>     <artifactId>Bot-Name</artifactId>
>     <version>1.0-SNAPSHOT</version>
> 
>     <properties>
>         <java.version>17</java.version>
>         <whatsapp4j.version>3.4.8</whatsapp4j.version>
>         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>         <maven.compiler.source>17</maven.compiler.source>
>         <maven.compiler.target>17</maven.compiler.target>
>     </properties>
> 
>     <build>
>         <plugins>
>             <plugin>
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-compiler-plugin</artifactId>
>                 <version>3.8.1</version>
>                 <configuration>
>                     <source>${java.version}</source>
>                     <target>${java.version}</target>
>                     <release>${java.version}</release>
>                     <compilerArgument>--enable-preview</compilerArgument>
>                     <compilerArgs>--enable-preview</compilerArgs>
>                 </configuration>
>             </plugin>
>             <plugin>
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-shade-plugin</artifactId>
>                 <version>3.2.4</version>
>                 <executions>
>                     <execution>
>                         <phase>package</phase>
>                         <goals>
>                             <goal>shade</goal>
>                         </goals>
>                         <configuration>
>                             <createDependencyReducedPom>false</createDependencyReducedPom>
>                         </configuration>
>                     </execution>
>                 </executions>
>             </plugin>
>             <plugin>
>                 
>                 <groupId>org.apache.maven.plugins</groupId>
>                 <artifactId>maven-jar-plugin</artifactId>
>                 <version>3.1.0</version>
>                 <configuration>
>                     <archive>
>                         <manifest>
>                             <addClasspath>true</addClasspath>
>                             <classpathPrefix>lib/</classpathPrefix>
>                             <mainClass>me.bot.base.Main</mainClass>
>                         </manifest>
>                     </archive>
>                 </configuration>
>             </plugin>
>         </plugins>
>         <resources>
>             <resource>
>                 <directory>src/main/resources</directory>
>                 <filtering>true</filtering>
>             </resource>
>         </resources>
>     </build>
> 
>     <repositories>
>         <repository>
>             <id>jcenter</id>
>             <name>jcenter-bintray</name>
>             <url>https://jcenter.bintray.com</url>
>         </repository>
>     </repositories>
> 
>     <dependencies>
>         
>         <dependency>
>             <groupId>junit</groupId>
>             <artifactId>junit</artifactId>
>             <version>4.13.2</version>
>             <scope>test</scope>
>         </dependency>
>         
>         <dependency>
>             <groupId>org.projectlombok</groupId>
>             <artifactId>lombok</artifactId>
>             <version>1.18.20</version>
>             <scope>provided</scope>
>         </dependency>
> 
>         <dependency>
>             <groupId>com.github.auties00</groupId>
>             <artifactId>whatsappweb4j</artifactId>
>             <version>${whatsapp4j.version}</version>
>         </dependency>
> 
> 
>     </dependencies>
> </project>
> 
> 
> 
> 

This is not a bug of the library, please search online how to build a jar with dependencies using Maven
https://stackoverflow.com/questions/574594/how-can-i-create-an-executable-runnable-jar-with-dependencies-using-maven
Also make sure that your main class is actually where it is

**Comment by GomesDev0001** [comment]
So, I've already checked in all ways, without your api the same src works, but with the api it gives this error..., could you help me? I've already seen all these documentaries, I've already called other professionals, none of them understand what happens, besides all recommend opening a support in the api.

**Comment by GomesDev0001** [comment]
So, I've already checked in all ways, without your api the same src works, but with the api it gives this error..., could you help me? I've already seen all these documentaries, I've already called other professionals, none of them understand what happens, besides all recommend opening a support in the api.

**Comment by Auties00** [comment]
> So, I've already checked in all ways, without your api the same src works, but with the api it gives this error..., could you help me? I've already seen all these documentaries, I've already called other professionals, none of them understand what happens, besides all recommend opening a support in the api.

as i said it's not an issue of the api, you are  not building the jar correctly. Don't use the IntelliJ build system to build a maven jar, use mvn package. Also make sure that your main class actually exists
