### ISSUE TITLE
Chat.java  displayName is null

### ISSUE THREAD

**Issue by xianliu18** [Auties00/Cobalt#335]
sync history chat, I log.info("chat: {}", JsonUtils.writeValueAsString(chat))  found, "displayName": null.

Can I get displayName of a chat, because chat.name is still a phone number.

**Comment by Auties00** [comment]
use name, not displayName

**Comment by xianliu18** [comment]
Where can I get a contact's nickname？ Because chat.name is a phone number, no nickname.
