### ISSUE TITLE
How to generate message public key and message private key by myself?

### ISSUE THREAD

**Issue by CanvaChen** [Auties00/Cobalt#354]
Hi, I’m interested in your project and I want to know how to generate message public key and message private key by myself. I know that these keys are usually stored in the axolotl.db file under the path /data/data/com.whatsapp/databases/, but I want to create them from scratch. Could you please explain the format and algorithm of these keys? Thank you.

**Comment by Auties00** [comment]
> Hi, I’m interested in your project and I want to know how to generate message public key and message private key by myself. I know that these keys are usually stored in the axolotl.db file under the path /data/data/com.whatsapp/databases/, but I want to create them from scratch. Could you please explain the format and algorithm of these keys? Thank you.

honestly I've got no idea, I implemented the mobile protocol by reversing the web one first.
