### ISSUE TITLE
RegistrationHelper doesn't handle captcha error while verification code requesting

### ISSUE THREAD

**Issue by hamarna** [Auties00/Cobalt#369]

**Comment by Auties00** [comment]
> 

That's intended, unless I'm missing something here

**Comment by hamarna** [comment]
I'm using RegistrationHelper and generating Whatsapp object via Store.random() and Keys.random().

RegistrationHelper.requestVerificationCode throws exception with VerificationResponse. Response has type "CAPTCHA" and there's no way to handle captcha and send it to WA when you register an mobile account manually.

**Comment by Auties00** [comment]
Tracking in https://github.com/Auties00/Cobalt/issues/371
