### ISSUE TITLE
Can not find method “toEncodedProtobuf”.

### ISSUE THREAD

**Issue by wangxingge** [Auties00/Cobalt#377]
all errors in the picture, include callstack, parameter, class name ,class method.
this error occurs when socket onOpen method.
![image](https://github.com/Auties00/Cobalt/assets/4143166/78d3f074-07ef-4107-8b3b-a48246f2a09d)

**Comment by Auties00** [comment]
> all errors in the picture, include callstack, parameter, class name ,class method.
> this error occurs when socket onOpen method.
> ![image](https://github.com/Auties00/Cobalt/assets/4143166/78d3f074-07ef-4107-8b3b-a48246f2a09d)
> 

Read the documentation, you need to delegate build actions to maven. It's explained in the readme

**Comment by wangxingge** [comment]
resolved. thanks
