### ISSUE TITLE
node timed out exception

### ISSUE THREAD

**Issue by sailer132** [Auties00/Cobalt#383]
![image](https://github.com/Auties00/Cobalt/assets/18714567/b9538be1-4674-4b57-9e92-c7bf1a8d2d15)
![image](https://github.com/Auties00/Cobalt/assets/18714567/a2433a40-06f3-4ac7-989f-c3f5f2782fff)

**Comment by Auties00** [comment]
When does this happen?

**Comment by sailer132** [comment]
when i send a message to a personal account,the bussiness api don't have that problem

**Comment by sailer132** [comment]
At first i send a message ,it success,but after 1 or 2 days later,i can't send the message ,there is a node timed out exception

**Comment by apricotwtf** [comment]
Related to #392?

**Comment by Auties00** [comment]
Yes
