### ISSUE TITLE
authhandler error

### ISSUE THREAD

**Issue by chenyangbo3** [Auties00/Cobalt#387]
When I receive serverclient and send ClientFinish. Will receive failed nodes.
error:
Node[description=failure, attributes={reason=401, location=atn}]

mark:
I login with the key.
![1694532594888](https://github.com/Auties00/Cobalt/assets/17523531/7b4cf9cf-c813-4e33-8819-96cddc215e2b)

**Comment by Auties00** [comment]
This is not an issue with the library, you simply can't login using those keys / they are wrong
