### ISSUE TITLE
Channels support

### ISSUE THREAD

**Issue by mircoianese** [Auties00/Cobalt#388]
Hello, 
I was testing your library with the brand new WhatsApp channels, but I don't think these are yet supported.

I see from the WhatsApp Web interface that I have a new button on my Business Account:
![image](https://github.com/Auties00/Cobalt/assets/22716366/090ab34d-38a6-4862-a7b4-924ca278d9d5)

From this I can see all the channels I have created and can also send messages to them.

If you need more info or anything for testing you can contact me privately.
Thanks for the amazing library!

**Comment by Auties00** [comment]
Working on this as a private project
