### ISSUE TITLE
How to handle READ status of my messages?

### ISSUE THREAD

**Issue by SachukS** [Auties00/Cobalt#389]
I have managed to handle DELIVERED status with onAnyMessageStatus and onConversationMessageStatus. But noone method, containing 'status' in its name, isn't called when status is changed (READ, ERROR etc.). I'm using 3.5.1. Thanks for your work!

**Comment by Auties00** [comment]
This is a bug in 3.5.1

**Comment by Auties00** [comment]
Fixed
