### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by ClarissaGazalaEvanthe** [Auties00/Cobalt#391]
I don't have java experience, please provide/make a flutter library

**Comment by Auties00** [comment]
You could use kotlin multiplatform to create bindings for Android and IOS and then using platform channels invoke those bindings. Still I don't have plans to work on this myself

**Comment by Sanim27** [comment]
after i setup path variable and ran flutter doctor i got this message :- Exception: Flutter failed to create a directory at "/Users/sanimpandey/.config/flutter".
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

**Comment by Auties00** [comment]
> after i setup path variable and ran flutter doctor i got this message :- Exception: Flutter failed to create a directory at "/Users/sanimpandey/.config/flutter".
> Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
> 

This isn't the place to ask for flutter support as it has nothing to do with this library

**Comment by Auties00** [comment]
> after i setup path variable and ran flutter doctor i got this message :- Exception: Flutter failed to create a directory at "/Users/sanimpandey/.config/flutter".
> Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.
> 

This isn't the place to ask for flutter support as it has nothing to do with this library

**Comment by developerfyp** [comment]
> You could use kotlin multiplatform to create bindings for Android and IOS and then using platform channels invoke those bindings. Still I don't have plans to work on this myself

you can flutter, please make it support

**Comment by codespearhead** [comment]
I wonder what use case calls for a Flutter port of the project, since the whole point of having an API is to not have to rely on a mobile device.

**Comment by Auties00** [comment]
> I wonder what use case calls for a Flutter port of the project, since the whole point of having an API is to not have to rely on a mobile device.

flutter desktop is a thing and it's very good, but realistically you can easily invoke the java apis under the hood.
For android and ios support, sorry but it looks like Kotlin native doesn't support java libraries (should have been obvious i guess), so I won't add support for this feature
