### ISSUE TITLE
WhatsApp create qr code to login into original device

### ISSUE THREAD

**Issue by melodic456** [Auties00/Cobalt#401]
Is there any way I can use this Library for logging into my android device directly? I mean if I login using your library, then at a time later I want to use that WhatsApp in my android? Can I do just qrcode scan to login to whatsapp using my android?

**Comment by Auties00** [comment]
You could like your android device as a companion or write some utility to export this library's keys for Android and load them there. I'm not going to work on this though

**Comment by melodic456** [comment]
Can you guide me a bit where to look inside your code? I can add this feature if you let me do it.. But I need the first guide where to start.
