### ISSUE TITLE
Question: Get information from Whatsapp Channels

### ISSUE THREAD

**Issue by josefschauer** [Auties00/Cobalt#408]
This is not a bug; it's more of a question or a feature request.

With my connection, it's only possible to get the status of users. 

But at the moment it's impossible to get information from (broadcast) channels.

Is this possible and/or already planned?

**Comment by Auties00** [comment]
Are you taking about newsletters or broadcast lists?

**Comment by josefschauer** [comment]
https://faq.whatsapp.com/549900560675125/?helpref=hc_fnav

It's a new feature and as far as I got it, not available everywhere at the moment.

**Comment by Auties00** [comment]
> https://faq.whatsapp.com/549900560675125/?helpref=hc_fnav
> 
> It's a new feature and as far as I got it, not available everywhere at the moment.

I've added support, use the master branch
