### ISSUE TITLE
"No routes" error while using mobile builder

### ISSUE THREAD

**Issue by hayimzvik** [Auties00/Cobalt#413]
I am attempting to register a new number as a `mobileBuilder` using the code snippet below. However, I am encountering a "no_routes" error from the registration phase ("/code").
 I have tried multiple prepaid numbers from the same provider in Cyprus, but the issue persists.
I'm using numbers that never had a WhatsApp account installed on them if it is relevant.
I can get the SMS using an actual device, so the problem isn't the number itself, I think.
Am I doing something wrong?
Thanks!

Code:
```java
Whatsapp api = Whatsapp.mobileBuilder()
        .newConnection()
        .unregistered()
        .verificationCodeMethod(VerificationCodeMethod.SMS)
        .verificationCodeSupplier(() -> {
            System.out.println("Enter OTP: ");
            var scanner = new Scanner(System.in);
            return CompletableFuture.completedFuture(scanner.nextLine());
        })
        .register(357XXXXXXL)
        .join();
```

Error:
```
 Exception in thread "main" java.util.concurrent.CompletionException: 
 it.auties.whatsapp.exception.RegistrationException: 
 VerificationCodeResponse[number=357XXXXXXX, 
 			lid=0, status=ERROR, errorReason=NO_ROUTES, method=null, 
 			codeLength=0, notifyAfter=0, retryAfter=3600, 
 			voiceLength=0, voiceWait=0, smsWait=0, whatsappOtpWait=0, 
 			flashType=0, oldWait=0, securityCodeSet=false, 
 			whatsappOtpEligible=false, imageCaptcha=null, 
 			audioCaptcha=null]
```

**Comment by MelonAlien** [comment]
> This is normal. Due to WhatsApp’s risk control, an Authorization parameter is missing in the request header.

Bro, I solved Authorization but it's still 1 hour.
Can we talk? https://t.me/Zqrow
