### ISSUE TITLE
after i invoke the changeProfilePicture api ,there is a: [toMap={reason=403, location=cln}],node.content:null

### ISSUE THREAD

**Issue by sailer132** [Auties00/Cobalt#419]

**Comment by Auties00** [comment]
> 

You are using the mobile api?

**Comment by sailer132** [comment]
> > 
> 
> You are using the mobile api?

yes

**Comment by Auties00** [comment]
This issue is related to Whatsapp's risk control for the mobile api, I won't fix this issue in the public repo

**Comment by sailer132** [comment]
how can i get the private repo,i can pay for U&nbsp;




sailor
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Auties00/Cobalt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月20日(星期三) 凌晨5:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Auties00/Cobalt] after i invoke the changeProfilePicture api ,there is a: [toMap={reason=403, location=cln}],node.content:null (Issue #419)





 
This issue is related to Whatsapp's risk control for the mobile api, I won't fix this issue in the public repo

**Comment by Auties00** [comment]
Contact me on telegram @Auties00
