### ISSUE TITLE
the method build is undefined for the all types OptionBulder

### ISSUE THREAD

**Issue by roxf18** [Auties00/Cobalt#420]
Hi Auties00
Hello, I have written this code according to your example in a MAVEN project, but I am facing this error
        Whatsapp.webBuilder()
                .lastConnection()
                .build()//the method build is undefined for the WebOptionBuilder?????????????
                .addLoggedInListener(() -> System.out.println("Connected!"))
                .addNewMessageListener(TesterBot::onNewMessage)
                .connectAndAwait()
                .join();

thanks

**Comment by Auties00** [comment]
> Hi Auties00
> Hello, I have written this code according to your example in a MAVEN project, but I am facing this error
>         Whatsapp.webBuilder()
>                 .lastConnection()
>                 .build()//the method build is undefined for the WebOptionBuilder?????????????
>                 .addLoggedInListener(() -> System.out.println("Connected!"))
>                 .addNewMessageListener(TesterBot::onNewMessage)
>                 .connectAndAwait()
>                 .join();
> 
> thanks

The documentation isn't up to date with the master branch. When I release the First stable cobalt release, I'll update it. In the meantime, use the source as a documentation
