### ISSUE TITLE
How do I write my store and keys for the new version？

### ISSUE THREAD

**Issue by orionnyqx** [Auties00/Cobalt#431]
I looked at the source code and found that the new version canceled the of constructor. In the past I only needed 7 parameters to build the keys object, now I need 26 parameters. For example, registrationId was generated through KeyHelper.registrationId() in the old version. Now I have to generate it myself.

**Comment by Auties00** [comment]
Will add in 0.0.2

**Comment by Auties00** [comment]
Added support already, check ControllerSerializer, Store#newStore, Keys#newKeys, StoreBuilder and KeysBuilder

**Comment by orionnyqx** [comment]
> Added support already, check ControllerSerializer, Store#newStore, Keys#newKeys, StoreBuilder and KeysBuilder

Can you give me an example? I checked keysBuilder and I found that it still needs to fill in a lot of parameters.

**Comment by Auties00** [comment]
> > Added support already, check ControllerSerializer, Store#newStore, Keys#newKeys, StoreBuilder and KeysBuilder
> 
> 
> 
> Can you give me an example? I checked keysBuilder and I found that it still needs to fill in a lot of parameters.

Use Keys.newKeys if you don't know how to fill it out

**Comment by orionnyqx** [comment]
> Use Keys.newKeys if you don't know how to fill it out

I used newKeys and got an error message saying Cannot invoke "it.auties.whatsapp.controller.ControllerSerializer.serializeKeys(it.auties.whatsapp.controller.Keys, boolean)" because "this.serializer" is null
