### ISSUE TITLE
method:sendMessage Will cause the whatsapp account was banned

### ISSUE THREAD

**Issue by zhouao** [Auties00/Cobalt#433]
As long as "sendMessage()" is used to send messages, the WhatsApp account will be immediately blocked

**Comment by Auties00** [comment]
> As long as "sendMessage()" is used to send messages, the WhatsApp account will be immediately blocked

If the account was just created, that's just a measure to prevent spamming. Business accounts don't have this limitation

**Comment by zhouao** [comment]
I used the whatsapp business account and sent it as "hi", which was banned in a second.

**Comment by Auties00** [comment]
Pretty sure this is an anti spam measure, but maybe the device has to be trusted before or something so I'll leave it open

**Comment by seanchan** [comment]
same issue banned when use sendMessage . 
it's a normal account when send messages in apk app , but banned when send message in code

**Comment by Auties00** [comment]
won't fix in the public version, this is caused by Whatsapp's risk control.
I could release a public fix, but then they'll just patch it so if you need it contact me on telegram
