### ISSUE TITLE
startcall error

### ISSUE THREAD

**Issue by sailer132** [Auties00/Cobalt#441]
when i invoke the startcall api ,there have a error :Node[description=call, attributes={to=***@s.whatsapp.net, id=0586a4661a}, content=[Node[description=offer, attributes={call-creator=***.0:0@s.whatsapp.net, call-id=a21565fee5, device_class=2016}, content=[Node[description=audio, attributes={rate=8000, enc=opus}], Node[description=audio, attributes={rate=16000, enc=opus}], Node[description=net, attributes={medium=3}], Node[description=enc, attributes={v=2, count=0, type=msg}, content=[51, 10, 33, 5, 27, -88, -75, -15, -88, -124, -38, 60, 22, -116, 78, -26, -16, 5, 36, 48, 79, -26, -23, -8, -73, -5, 96, -9, -114, 113, 74, 60, -93, -66, -127, 22, 34, 64, 39, 93, 51, 107, 91, -122, 54, -49, -76, 91, 61, 22, -86, -40, -98, 114, 57, -27, -116, -8, 67, -95, 80, -39, -116, 84, -109, 12, -61, 38, -70, 110, 59, -72, -10, 100, -118, 13, -18, 98, 101, -51, 105, 81, -95, -85, -30, 121, 98, 76, -94, 54, -91, 51, -105, 105, 80, -121, -46, -5, -102, -35, 2, -66, 16, 2, 24, 0, -52, 58, 17, 88, -58, 89, -68, 83]], Node[description=capability, attributes={ver=1}, content=�	�:], Node[description=encopt, attributes={keygen=2}]]]]] node timed out

**Comment by Auties00** [comment]
Are you using the mobile api?

**Comment by sailer132** [comment]
yes i'm sure i use the mobile api

**Comment by Auties00** [comment]
fixed
