### ISSUE TITLE
Java 17 Support

### ISSUE THREAD

**Issue by ivys-m** [Auties00/Cobalt#445]
Hi I'd love to use this library for a project, however the project is built using Java 17.
I understand, as stated in the readme, that the library is built for Java 21 but I was wondering if there was any chance you had a stable version for Java 17.
I was hoping to find one from the previous commits but I came too late and now they're gone.
Would you be able to help me?

I looked at some other issues and discussions trying to find something similar but I couldn't find anything.
I'm sorry if you already answered this in a different issue and I missed it.

Thanks and have a good day.

**Comment by Auties00** [comment]
No there's no stable version for Java 17 unfortunately
