### ISSUE TITLE
RawSocketSession does not seem to support socks5 proxy. Can it be supported?

### ISSUE THREAD

**Issue by snowfroghk** [Auties00/Cobalt#446]

**Comment by Auties00** [comment]
> _No description provided._

I could add support if it's needed, unfortunately it's not possible for the web socket(web api) without some big changes

**Comment by snowfroghk** [comment]
Thank you very much. In fact, the main reason is that mobile’s RawSocketSession requires the support of socks5 because not all regions can directly connect to the whatsapp server.

**Comment by Auties00** [comment]
added support
