### ISSUE TITLE
code sent but exist incorrect

### ISSUE THREAD

**Issue by CanvaChen** [Auties00/Cobalt#449]
> /code: {"status":"sent","length":6,"retry_after":125,"method":"sms"...

but
> /exist: {"reason":"incorrect","status":"fail","sms_wait":0...

**Comment by Auties00** [comment]
> > /code: {"status":"sent","length":6,"retry_after":125,"method":"sms"...
> 
> 
> 
> but
> 
> > /exist: {"reason":"incorrect","status":"fail","sms_wait":0...

That's the expected response, don't even ask me why. I think that WhatsApp made it like this to confuse people reversing the api
