### ISSUE TITLE
Web Pairing Code lasts a very short time

### ISSUE THREAD

**Issue by gu1llermo** [Auties00/Cobalt#452]
Hello friend, first of all I wanted to congratulate you for such excellent work, and take the opportunity to ask you if it is possible for the pairing code to last longer? Because when I finally manage to write it it has already expired and is of no use. On WhatsApp it doesn't allow you to write it quickly.

**Comment by Auties00** [comment]
> Hello friend, first of all I wanted to congratulate you for such excellent work, and take the opportunity to ask you if it is possible for the pairing code to last longer? Because when I finally manage to write it it has already expired and is of no use. On WhatsApp it doesn't allow you to write it quickly.

Can you try with cobalt 0.0.3?

**Comment by gu1llermo** [comment]
I didn't know there was a 0.0.3 version. It's a matter of trying
