### ISSUE TITLE
ChatMessageKey.randomId() id attribute should be 32 length rather than 16 length in mobile, wonder if that's triggered the spam policy banned or not .

### ISSUE THREAD

**Issue by seanchan** [Auties00/Cobalt#455]
message I traced down in apk message shall be like :
`<message to='xxx@s.whatsapp.net' type='text' id='40272425120C18D9E40CCF65370E7FCD'><participants><to jid='xxx.0:1@s.whatsapp.net'><enc v='2' type='msg'>MwohBUrBOaJndqIzHKvzPQQAFtQD4BoVUVtogBCc3FjzZa8ZEIIBGAgikAGOWaR12vQ27vVKuPAzBGqcCA1xU63WLn0Uj4omc48dGs+qUtBnvLqAcnULSJn2nRcezdqQXw9v7qEaT5F3eq0qR01Ich+Lt2uPU8y15iL7uuSRv4BhPIGV/WbSlyW5oZgjLepZNHp/MxcHmpie7RgotpmnDRKceZpGYuv6v9KF5zkpPNNDbLxLF2jNB1cXz2x4a689+IdXVw==</enc></to></participants></message>`
with id attribute 32 length .

but I found the implementation  in code ChatMessageKey.randomId generate an ID with 16 length.
wonder if that's triggered the spam policy banned or not .

**Comment by seanchan** [comment]
debuged message with id 32 length only tested on android devices . 
not sure if ios device shows a different length

**Comment by Auties00** [comment]
This is not important, but if you want to fix it you can open a pr
