### ISSUE TITLE
403 If SendMessage with SixPartsKeys

### ISSUE THREAD

**Issue by dada12111** [Auties00/Cobalt#460]
When I use Whatsapp.mobileBuilder().newConnection(SixPartsKeys.of(str))
SendMessage returns 403 after a few seconds after success.

**Comment by Auties00** [comment]
Known issue being tracked in https://github.com/Auties00/Cobalt/issues/433
This issue is already fixed in the private repo, if you are interested contact me on telegram @auties00
Eventually it will come to the open source version as well
