### ISSUE TITLE
ProtobufControllerSerializer onError

### ISSUE THREAD

**Issue by Passeo** [Auties00/Cobalt#462]
I got this spam error . I'm using 0.0.3 , Login through Web QR Pairing

```
it.auties.whatsapp.controller.ProtobufControllerSerializer onError
SEVERE: java.util.concurrent.CompletionException: java.nio.file.InvalidPathException: Illegal char <:> at index 18: chat_628515535xxxx:84@s.whatsapp.net.proto7456036244367391470.tmp
```

**Comment by Auties00** [comment]
> I got this spam error . I'm using 0.0.3 , Login through Web QR Pairing
> 
> ```
> it.auties.whatsapp.controller.ProtobufControllerSerializer onError
> SEVERE: java.util.concurrent.CompletionException: java.nio.file.InvalidPathException: Illegal char <:> at index 18: chat_628515535xxxx:84@s.whatsapp.net.proto7456036244367391470.tmp
> ```

Fixed in 0.0.4
