### ISSUE TITLE
Nodes aren't being received

### ISSUE THREAD

**Issue by Darker935** [Auties00/Cobalt#485]
I'm experiencing a problem with all node receipts, and I didn't find the reason, as no crash log appears

The sessions works fine for a long time, but in a random moment, it stops to receive any messages/node updates, except ping requests:

```
[RECEIVED] Node[description=iq, attributes={xmlns=urn:xmpp:ping, t=1714253376, from=s.whatsapp.net, type=get}]
[SENT] Node[description=iq, attributes={xmlns=w:p, to=s.whatsapp.net, type=get, id=1714242147-13}, content=[Node[description=ping]]]
[RECEIVED] Node[description=iq, attributes={t=1714253376, from=s.whatsapp.net, id=1714242147-13, type=result}]
[SENT] Node[description=iq, attributes={xmlns=w:p, to=s.whatsapp.net, type=get, id=1714242147-14}, content=[Node[description=ping]]]
[RECEIVED] Node[description=iq, attributes={t=1714253406, from=s.whatsapp.net, id=1714242147-14, type=result}]
```

When I leave the session offline, and try to reconnect on the next day, the pending messages and nodes are synced, but when it sync all pending messages and come again to current messages/nodes, it stops again

If more logs is needed, text me on [Telegram](https://t.me/DarkerZap) and I'll send the complete logs, like when I start the session

**Comment by Auties00** [comment]
Tracking in https://github.com/Auties00/Cobalt/issues/458
