### ISSUE TITLE
Failed to add cobalt:0.0.5 as dependency

### ISSUE THREAD

**Issue by atasc** [Auties00/Cobalt#501]
Hi,
Adding cobalt:0.0.5 as dependency to build.gradle generates an exception:

```
implementation 'com.github.auties00:cobalt:0.0.5'
annotationProcessor 'com.github.auties00:cobalt:0.0.5'
```

The exception is as follows:

```
[Fatal Error] cobalt-0.0.5.pom:3:1: Content is not allowed in prolog.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve com.github.auties00:cobalt:0.0.5.
     Required by:
         project :
      > Could not resolve com.github.auties00:cobalt:0.0.5.
         > Could not parse POM https://repo.maven.apache.org/maven2/com/github/auties00/cobalt/0.0.5/cobalt-0.0.5.pom
            > Content is not allowed in prolog.
```

It seems that the pom.xml file might be malformed. Accessing the POM file at the following URL:

https://repo.maven.apache.org/maven2/com/github/auties00/cobalt/0.0.5/cobalt-0.0.5.pom

gives the error:

This page contains the following errors:
error on line 1 at column 7: XML declaration allowed only at the start of the document
Below is a rendering of the page up to the first error.

My enviromnent is Jdk 21 and Gradle 8.8,

**Comment by Darker935** [comment]
Already tracked on #495
