### ISSUE TITLE
get account creation date

### ISSUE THREAD

**Issue by dannywynn** [Auties00/Cobalt#502]
what node should i send to get this response

```xml
<iq from="s.whatsapp.net" type="result" id="XXXXXX">
  <account creation="1715766530" last_reg="1718678913" />
</iq>
```

**Comment by dannywynn** [comment]
i got this from a friend and he got this from russian guy 
he sell this tool that can get creation date

**Comment by Auties00** [comment]
Added with queryAccountInfo in 0.0.6
