### ISSUE TITLE
Is there an ability to handle multiple accounts in multithreads?

### ISSUE THREAD

**Issue by SachukS** [Auties00/Cobalt#504]
I'm developing Java Spring server for telegram and whatsapp messengers, and i want to know is there an ability to handle multiple whatsapp accounts in one time? Thanks for your work

**Comment by Darker935** [comment]
I think if you change:
```java
.newConnection().name("YourSessionName")
```you can operate with more than 1 session per time, try and report

**Comment by Darker935** [comment]
It worked?

**Comment by SachukS** [comment]
> It worked?

Yea, it worked in such way. Sorry for late response, was busy with another staff

**Comment by Darker935** [comment]
No problem! If you have no further questions, you can close the issue now

**Comment by SachukS** [comment]
> I think if you change this code:
> 
> ```java
> .newConnection().name("YourSessionName")
> ```
> 
> on your login logic, you can operate with more than 1 session per time. Try and report
> 
> that's an exapmle of login (after register):
> 
> ```java
> var whatsapp = mobileBuilder()
>     .newConnection()
>     .name("Account-1")
>     .device(CompanionDevice.ios(false))
>     .autodetectListeners(true)
>     .registered()
>     .orElseThrow();
> ```


After deep testing i've found better way to implement functional i need:
```java
Whatsapp api = Whatsapp.webBuilder()
                    .newConnection(partner.getPhone())
                    .name("your messenger tool name")
                    .unregistered(onQRCode());
```
