### ISSUE TITLE
Error sending Message to Group with new Session

### ISSUE THREAD

**Issue by piLovr** [Auties00/Cobalt#510]
I build a simple recieve Message -> send Message example with a messageListener. In private chat (x@s.whatsapp.net) it works fine. (Web) Bot responds with a simple Text message `client.sendMessage(from,"Hello")`. But in groups I get the never changing Message called "_Waiting for this message. This may take a while. Learn more_".
This happened before on a new Session, in fact I was never able to see a message of my Bot in a group

**Comment by piLovr** [comment]
works now, still a weird bug I guess

**Comment by Auties00** [comment]
Should be fixed in 0.0.6 with message retries
