### ISSUE TITLE
method; fetchAllParticipating

### ISSUE THREAD

**Issue by piLovr** [Auties00/Cobalt#511]
idk if something like this exists, if yes, I wasn't able to find it. I need a list of groups, in which a session is participating. The "onChats" listener shows all chats, even though I am no more a part of it.

**Comment by Auties00** [comment]
queryGroupMetadata
Then call participants()

**Comment by piLovr** [comment]
I need a method to get all Jids/Metadata of the Groups, in which a session is participating

session.fetchAllParticipating() -> Collection<Jid>

something like that

**Comment by piLovr** [comment]
Nvm, got it. Chats list via store
