### ISSUE TITLE
Waiting for this message. this may take a while

### ISSUE THREAD

**Issue by DouglasSilv** [Auties00/Cobalt#522]
I'm having a problem where, after some time of conversation, the messages sent by the bot are not being loaded for the recipient. Has anyone had this problem? Do you know how to solve it?
![image](https://github.com/user-attachments/assets/8a63891b-20bd-4ccf-9404-70b547aae7d6)

**Comment by Auties00** [comment]
Fixed in the latest version, I will push it soon
