### ISSUE TITLE
How to decrypt .enc received media file from whatsapp?

### ISSUE THREAD

**Issue by vlindberg** [Auties00/Cobalt#526]
When I receive an image from WhatsApp I have the mediaUrl (.enc file) and mediaKey attributes. How do I get the decrypted byte array of the image?

**Comment by vlindberg** [comment]
I found how to do it:

Optional<byte[]> opt = api.downloadMedia(img).get();

**Comment by vlindberg** [comment]
I found how to do it:

Optional<byte[]> opt = api.downloadMedia(img).get();

**Comment by Auties00** [comment]
> I found how to do it:
> 
> Optional<byte[]> opt = api.downloadMedia(img).get();

Yeah this is the correct answer

**Comment by Auties00** [comment]
> > I found how to do it:
> > Optional<byte[]> opt = api.downloadMedia(img).get();
> 
> Yeah this is the correct answer

It will be likely impossible very soon. 
I’m rewriting the entire network stack at https://github.com/Auties00/Leap and that uses kernel functions for tcp and udp sockets. I could take a look and check how Android does it and add support though
